### ISSUE TITLE
webhook verify dones not work.

### ISSUE THREAD

**Issue by formobi** [cashfree/cashfree-pg-sdk-nodejs#64]

**Comment by formobi** [comment]
Tried using  following function, it does not work. changed it to get, it gets executed but gives error.
app.post('/webhook', function (req, res) {
    try {
        Cashfree.PGVerifyWebhookSignature(req.headers["x-webhook-signature"], req.rawBody, req.headers["x-webhook-timestamp"]))
    } catch (err) {
        console.log(err.message)
    }
})

**Comment by suhas-cashfree** [comment]
How are you using this ?

**Comment by suhas-cashfree** [comment]
Once you register for a webhook with Cashfree, that is the end-point which is given in the example.

**Comment by formobi** [comment]
1> Do you mean registering via api as "return_url"? I have seen some places
notify_url too OR registering on cashfree dashboard?
2> If I provide GET instead of post then the webhook gets called. But the
headers do not have signatures.

Can you please point me to working example of cordova+nodejs.

**Comment by suhas-cashfree** [comment]
1> Do you mean registering via api as "return_url"? I have seen some places
notify_url too OR registering on cashfree dashboard?

You can use "notify_url" or register from cashfree dashboard.

2> If I provide GET instead of post then the webhook gets called. But the
headers do not have signatures.

May be you are setting "return_url". Return Url is used redirect the user post payment. You have to use "notify_url" or register from dashboard

**Comment by formobi** [comment]
Can you please Poon me to the documents which clarify it.

**Comment by suhas-cashfree** [comment]
https://docs.cashfree.com/docs/configure-webhooks

**Comment by suhas-cashfree** [comment]
Closing this for now. Please create a new ticket if the issue persists
